<? include("./init.inc") ?>
<!DOCTYPE html>
<html lang="de">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><?php echo $siteTitle ?></title>
  <meta name="description" content="<?php echo $siteDescription ?>">
  <meta property="og:title" content="<?php echo $siteTitle ?>">
  <meta property="og:description" content="<?php echo $siteDescription ?>">
  <meta property="og:image" content="<?php echo $siteImage->size(1200, 630)->HTTPURL ?>">
  <link href="/css/materialize.min.css" type="text/css" rel="stylesheet" media="screen">
  <link href="/css/style.css" type="text/css" rel="stylesheet" media="screen">
  <link href="/css/prism.css" type="text/css" rel="stylesheet" media="screen">
  <script src="/js/spotlight.bundle.js"></script>
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
  <link rel="manifest" href="/site.webmanifest">
  <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#006eb7">
  <meta name="msapplication-TileColor" content="#006eb7">
  <meta name="theme-color" content="#ffffff">
</head>
<body>
