<?php
include("./includes/head.inc");
include("./includes/header.inc");
include("./includes/slider.inc");
include("./includes/simple-body.inc");
include("./includes/shortcuts.inc");
include("./includes/article-list.inc");
include("./includes/events-table.inc");
include("./includes/foot.inc");
